services:
  # postgres:
  #   image: postgres:14.13-alpine3.20
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./_docker_volumes/postgres:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=standard
  #     - POSTGRES_PASSWORD=Codium123!

  # redis:
  #   image: redis:6.2.14-alpine3.20
  #   volumes:
  #     - ./_docker_volumes/redis:/data

  django:
    # depends_on:
    #   - postgres
    #   - redis
    build:
      context: ./backend
    command: tail -f /dev/null
    ports:
      - 8000:8000
    volumes:
      - ./backend:/opt/app
    # env_file:
    # - .env

  react:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:opt/app
    command: tail -f /dev/null
